server:
  port: 10001

spring:
  application:
    name: ky-api
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ky?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB
# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dayi.entity
  configuration:
    # can get id while saving data
    use-generated-keys: true

#logging:
#  file:
#    path: D:/develop/testLog/
#  level:
#    com.dy: info

dy:
  resource:
    docs: classpath:/docs/
    images: D:/develop/images/
  build:
    data-center-id: 1
    machine-id: 1

